---
title: "Project Reviews"
author: "George Guarnieri"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The first project that I am reviewing is Neil Khurana's "Harvard Dining." The first thing I noted about this project was the way that Neil gathered his data. I was impressed with the scope of his data gathering and the script that he used in order to do so. I think that the greatest pro to this project is that the project is based on a subject that is genuinely engaging to the student body. It is a dataset that answers questions I posed many times throughout freshman year, such as does Annenberg serve the same food every day of the week? Or, do they serve popcorn chicken every Monday? The biggest con to the project that stood out to me was the aesthetics of the plot. I felt like a bit more could have been done in order to highlight important aspects of the data, or add a more professional element to it. 

The second project that I am reviewing is Tanner Gildea's "2020 Democratic Candidates' Tweets." I think that the most impressive thing about this project is the way the dataset was put together. I would imagine that accumulating and collecting all of the data from different candidates' tweets would be a difficult process. However, I think that the project's use of data that is not readily available or cleaned makes for a more interesting final project. Additionally, I thought that project does a great job with its different visualizations. They all appeared extremely professional to me and had excellent aesthetic elements. I also enjoyed the interactive element of the interface, which allowed me to do things such as select specific candidates, or search for certain key terms. One aspect of the project that I beleieve can be improved relates to the key terms search. I noticed that very common words and phrases such as "its" were not filtered out. I think that finding a way to filter out typical words in a sentence, as opposed to words that are truly indicative of candidate sentiment, would be extremely useful. 


